type = Quantifier
name = test
analysis_type = QUINT
quantifier_input_dir = Q2/Input
quantifier_atlas_dir = Q2/Atlasmap
label_file = Allen Mouse Brain 2015
custom_label_file = 
xml_anchor_file = Q2/Atlasmap/79556738.xml
quantifier_output_dir = Q2/Out
output_report = All
extraction_color = 255,255,255,255
object_splitting = No
object_min_size = 1
global_pixel_scale = 1
quantifier_pixel_scale_unit = pixels
use_custom_masks = Yes
custom_mask_directory = Q2/Masks
custom_mask_color = 255,255,255,255
output_report_type = CSV
custom_region_type = Default
custom_region_file = 
coordinate_extraction = All
coordinate_random_distortion = 0
pixel_density = 1
nifti_size = 0
display_label_id = No
output_region_id = No
pattern_match = _sXXX
files = 
nutil_version = v0.7.0


nutil_version = v0.7.0
