type = Transform
name = Transform Validator
output_compression = lzw
transform_input_dir = T_1/in
transform_output_dir = T_1/out
auto_crop = yes
transform_background_color = 255,255,255,255
transform_color_spread = 
transform_files = trse_256.tif,trse_256.tif,45,1,1
only_thumbnails = No
transform_thumbnail_size = 1.0
