name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        id: addItem
        with:
          project-url: https://github.com/orgs/Neural-Systems-at-UIO/projects/2
          github-token: ${{ secrets.ORG_KEY }}

      - uses: kalgurn/update-project-item-status@main
        with:
          project-url: https://github.com/orgs/Neural-Systems-at-UIO/projects/2
          github-token: ${{ secrets.ORG_KEY }}
          item-id: ${{ steps.addItem.outputs.itemId }}
          status: "To Do"
