name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

env:
  MY_GITHUB_TOKEN: ${{ secrets.ORG_KEY }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/Neural-Systems-at-UIO/projects/2'
        column_name: 'To Do'
    - name: Assign issues and pull requests with `bug` label to project 3
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: 
        contains(github.event.pull_request.labels.*.name, 'bug')
      with:
        project: 'https://github.com/orgs/Neural-Systems-at-UIO/projects/2'
        column_name: 'In Progress'
